### ISSUE TITLE
making a map of where all the species are in space

### ISSUE THREAD

**Issue by wcornwell** [jessicatytam/honours#12]
Have to first make a calculation of species of species centroid:

https://rmacroecology.netlify.app/2018/02/06/species-level-macroecological-analysis/

**Comment by wcornwell** [comment]
also see: https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13478#.X2oUr4FssQ8.twitter

**Comment by wcornwell** [comment]
![image](https://user-images.githubusercontent.com/5534161/95526325-376c2e80-0a20-11eb-8c64-1eed72c13dc0.png)

mammal species richness from GBIF

**Comment by wcornwell** [comment]
![image](https://user-images.githubusercontent.com/5534161/95529464-afd5ee00-0a26-11eb-8cf0-f085b190aa92.png)

and centroid of species ranges

**Comment by itchyshin** [comment]
This looks great! @wcornwell  - you can see Australia is a special place!

**Comment by jesstytam** [comment]
![logh_map](https://user-images.githubusercontent.com/51732676/106216881-2a21bc80-6228-11eb-8c79-4374982da4e8.png)
centroids of species with log(h)

**Comment by jesstytam** [comment]
i hope i am doing this right haha

**Comment by itchyshin** [comment]
@jessicatytam - high Hs are in US, Europe and Aus - so it is looking good!

**Comment by wcornwell** [comment]
Looks good to me too!

**Comment by jesstytam** [comment]
exclude domesticated mammals, make multiple versions
