### ISSUE TITLE
where to add h-index / altmetric / google trends?

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#19]
should I have the h-index / altmetric / google trends data in another dataframe? or should I add them to the one with mass / phylogeny / etc.?

**Comment by itchyshin** [comment]
@jessicatytam - whichever is easiest but probably separate for now? - depends on how you get h-index - which names are you using to get h-index?

**Comment by jesstytam** [comment]
i've got 8,000+ unique names after combing the datasets (i suspect there are many synonyms?), i'll push it to the outputs folder after adding classification levels

**Comment by itchyshin** [comment]
@jessicatytam - you probably have to figure out synonyms and map out to phylogeny you have.

@wcornwell and @mlagisz - is this right?

**Comment by jesstytam** [comment]
use latin name for googletrends
can ignore altmetrics for now

**Comment by jesstytam** [comment]
get the sum, slope, intercept for each species

**Comment by jesstytam** [comment]
use lm

**Comment by jesstytam** [comment]
use glm poisson
check error distribution

**Comment by jesstytam** [comment]
replace <1 with 0.5 for now
use centred intercept
only get the sum for now
