### ISSUE TITLE
synonym matching

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#20]
try taxize and rgbif

**Comment by jesstytam** [comment]
check if rotl uses taxize

**Comment by jesstytam** [comment]
what should I do with synonyms that have different data, e.g. different mass, iucn category?

**Comment by jesstytam** [comment]
![Screenshot from 2021-01-05 11-14-12](https://user-images.githubusercontent.com/51732676/103592558-6f174380-4f47-11eb-8730-05f1b7087c6d.png)

e.g. rows 196 and 203

**Comment by itchyshin** [comment]
@jessicatytam - we keep these data using long format - I think we may want to get all of them into a long format (but sharing species ID) Then, we can take average values or we think about it

Does it make sense?

**Comment by jesstytam** [comment]
ok so I'll keep them all for now, add species ID and remove duplicates if there is any
