### ISSUE TITLE
conservation keyword

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#28]
species name + "conservation" for all species
domesticated species higher h-index difference
use a bar plot
find out if they are partially / fully domesticated (add a column)
default is "not domesticated"
https://en.wikipedia.org/wiki/List_of_domesticated_animals

**Comment by jesstytam** [comment]
use "conserv*"
run for 1 species first
compare "conservation" & "conserv*"
check for irrelevant records

**Comment by jesstytam** [comment]
![logh_conserv](https://user-images.githubusercontent.com/51732676/109081777-e783cf00-7756-11eb-9d4b-ef78f379bd77.png)
will get data for "conservation" later

**Comment by itchyshin** [comment]
@jessicatytam - interesting - now the distribution is much like zero-inflated Poisson!

**Comment by jesstytam** [comment]
![logh_conserv](https://user-images.githubusercontent.com/51732676/109248958-e88e2c80-783a-11eb-8bc5-2d591b7a35b4.png)
I've added the keyword conservation in this one

**Comment by jesstytam** [comment]
conserv* is better

**Comment by jesstytam** [comment]
one axis with keyword, one without
colour by iucn status
geom_point

**Comment by jesstytam** [comment]
add this data to the master df
