### ISSUE TITLE
finalize selection of body size data

### ISSUE THREAD

**Issue by wcornwell** [jessicatytam/honours#3]
discussion of different data sources: see also #2

**Comment by itchyshin** [comment]
@jessicatytam  - try this function 

https://github.com/mastoffel/AnAgeScrapeR

to get all weights from AnAge and also see whether we can get weight from ADW

**Comment by itchyshin** [comment]
Rose said - you can use the R's rvest package to scrape weight data from ADW

@jessicatytam - try to learn it via 
These seem to be new
https://www.dataquest.io/blog/web-scraping-in-r-rvest/
https://towardsdatascience.com/tidy-web-scraping-in-r-tutorial-and-resources-ac9f72b4fe47
This seems old
http://zevross.com/blog/2015/05/19/scrape-website-data-with-the-new-r-package-rvest/

**Comment by itchyshin** [comment]
@jessicatytam - @mlagisz said she found - a paper with 5000 spp+ weight data - please add that dataset or ref here. We may not need to do all scrapping etc

**Comment by jesstytam** [comment]
this: http://www.esapubs.org/archive/ecol/E084/094/#data

**Comment by wcornwell** [comment]
Looks good to me!

**Comment by jesstytam** [comment]
I'm trying to scrape the data from ADW now and collate a big database for mass but I've noticed the other databases have a lot of data points with the value -999. Does this mean NA? Any ideas? (body_mass.R or the codes and mass_databases folder o the datasets)
Also should I include other non-body mass data as well? They seem to have some data on location / population density / status / etc. which could be useful.

**Comment by itchyshin** [comment]
-999 = missing values

**Comment by wcornwell** [comment]
Have we checked this one: https://figshare.com/collections/EltonTraits_1_0_Species-level_foraging_attributes_of_the_world_s_birds_and_mammals/3306933

Seems pretty good

**Comment by wcornwell** [comment]
4 data sources

- animal diversity web

- panthera

- Smith et al. 

- AnAge

plus maybe elton traits

first download everything and get into one dataframe

**Comment by wcornwell** [comment]
elton traits includes smith et al.

**Comment by wcornwell** [comment]
using eltontraits for now
