### ISSUE TITLE
ScopusAPI

### ISSUE THREAD

**Issue by itchyshin** [jessicatytam/Honours#3]
#Modified function from https://github.com/christopherBelter/scopusAPI
#FYI: https://dev.elsevier.com/apikey/managehome
#http://api.elsevier.com/documentation/SCOPUSSearchAPI.wadl#N1002B
#My API key: 29a25986f5fe26edfcaec8b3f3b42718

#Chris's original function
searchByString <- function(string, datatype = "application/xml", content = "complete", myStart = 0, retCount = 25, retMax = Inf, mySort = "-coverDate", outfile) {
  if (!datatype %in% c("application/xml", "application/json", "application/atom+xml")) { ## error checking for valid inputs to the function
    stop("Invalid datatype. Valid types are 'application/xml', 'application/json', and 'application/atom+xml'")
  }
  else if (!content %in% c("complete", "standard")) {
    stop("Invalid content value. Valid content values are 'complete', and 'standard'")
  }
  else {
    library(httr)
    library(XML)
    key <- "29a25986f5fe26edfcaec8b3f3b42718"
    print("Retrieving records.")
    theURL <- GET("http://api.elsevier.com/content/search/scopus", query = list(apiKey = key, query = string, sort = mySort, httpAccept = datatype, view = content, count = retCount, start = myStart)) ## format the URL to be sent to the API
    stop_for_status(theURL) ## pass any HTTP errors to the R console
    theData <- content(theURL, as = "text") ## extract the content of the response
    newData <- xmlParse(theURL) ## parse the data to extract values
    resultCount <- as.numeric(xpathSApply(newData,"//opensearch:totalResults", xmlValue)) ## get the total number of search results for the string
    print(paste("Found", resultCount, "records."))
    retrievedCount <- retCount + myStart ## set the current number of results retrieved for the designated start and count parameters
    while (resultCount > retrievedCount && retrievedCount < retMax) { ## check if it's necessary to perform multiple requests to retrieve all of the results; if so, create a loop to retrieve additional pages of results
      myStart <- myStart + retCount ## add the number of records already returned to the start number
      print(paste("Retrieved", retrievedCount, "of", resultCount, "records. Getting more."))
      theURL <- GET("http://api.elsevier.com/content/search/scopus", query = list(apiKey = key, query = string,  sort = mySort, httpAccept = datatype, view = content, count = retCount, start = myStart)) ## get the next page of results
      theData <- paste(theData, content(theURL, as = "text")) ## paste new theURL content to theData; if there's an HTTP error, the XML of the error will be pasted to the end of theData
      if (http_error(theURL) == TRUE) { ## check if there's an HTTP error
        print("Encountered an HTTP error. Details follow.") ## alert the user to the error
        print(http_status(theURL)) ## print out the error category, reason, and message
        break ## if there's an HTTP error, break out of the loop and return the data that has been retrieved
      }
      retrievedCount <- retrievedCount + retCount ## add the number of results retrieved in this iteration to the total number of results retrieved
      Sys.sleep(1)
    } ## repeat until retrievedCount >= resultCount
    print(paste("Retrieved", retrievedCount, "records. Formatting results."))
    writeLines(theData, outfile, useBytes = TRUE) ## if there were multiple pages of results, they come back as separate XML files pasted into the single outfile; the theData XML object can't be coerced into a string to do find/replace operations, so I think it must be written to a file and then reloaded; useBytes = TRUE keeps the UTF-8 encoding of special characters like the copyright symbol so they won't throw an error later
    theData <- readChar(outfile, file.info(outfile)$size) ## convert the XML results to a character vector of length 1 that can be manipulated
    theData <- gsub("<?xml version=\"1.0\" encoding=\"UTF-8\"?>", "", theData, fixed = TRUE, useBytes = TRUE)
    theData <- gsub("<search-results.+?>", "", theData, useBytes = TRUE)
    theData <- gsub("</search-results>", "", theData, fixed = TRUE) ## remove all headers and footers of the separate XML files
    theData <- paste("<?xml version=\"1.0\" encoding=\"UTF-8\"?><search-results xmlns=\"http://www.w3.org/2005/Atom\" xmlns:cto=\"http://www.elsevier.com/xml/cto/dtd\" xmlns:atom=\"http://www.w3.org/2005/Atom\" xmlns:prism=\"http://prismstandard.org/namespaces/basic/2.0/\" xmlns:opensearch=\"http://a9.com/-/spec/opensearch/1.1/\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\">", theData)
    theData <- paste(theData, "</search-results>") ## add the correct header to the beginning of the file and the correct footer to the end of the file
    writeLines(theData, outfile, useBytes = TRUE) ## save the correctly formatted XML file
    print("Done")
    return(theData) ## return the final, correctly formatted XML file
  }
}

#searchByString("Liolaemus laurenti", outfile = "test.L.laurenti.xml")

#My modified version
searchCount <- function(sp.name, datatype = "application/xml") {
    library(httr)
    library(XML)
    key <- "29a25986f5fe26edfcaec8b3f3b42718" #my api key
    a <- "TITLE-ABS-KEY(\""
    b <- "\")"
    theURL <- GET("http://api.elsevier.com/content/search/scopus", query = list(apiKey = key, query = paste(a, sp.name ,b) , httpAccept = datatype)) ## format the URL to be sent to the API
    stop_for_status(theURL) ## pass any HTTP errors to the R console
    theData <- content(theURL, as = "text") ## extract the content of the response
    newData <- xmlParse(theURL) ## parse the data to extract values
    resultCount <- as.numeric(xpathSApply(newData,"//opensearch:totalResults", xmlValue)) ## get the total number of search results for the string
   #print(paste("Found", resultCount, "records."))
    return(resultCount)
  }

#searchCount(string = "TITLE-ABS-KEY(\"Liolaemus laurenti\")")

**Comment by mlagisz** [comment]
Info how to register for Scopus API
https://johnmuschelli.com/rscopus/

**Comment by itchyshin** [comment]
@jessicatytam  - read this

I followed instructions from here :https://github.com/christopherBelter/scopusAPI
It directed you to get API here: https://dev.elsevier.com/
GitHubGitHub
christopherBelter/scopusAPI
Query the Scopus Search API in R and parse the results into a data frame - christopherBelter/scopusAPI
dev.elsevier.com
Elsevier Developer Portal
Elsevier APIs Developer Portal

1:46
My key is in the function, so you can try use it?

**Comment by wcornwell** [comment]
this is solved, i think
