### ISSUE TITLE
phylogeny

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#33]
![h_tree](https://user-images.githubusercontent.com/51732676/108014013-14522b00-7061-11eb-9e46-e9442fc761fb.png)

**Comment by wcornwell** [comment]
is this the code here?  https://github.com/jessicatytam/honours/blob/c6245dab83347e3bcd38bb895d5249bb1a5cddd6/R/plots.R#L511

**Comment by jesstytam** [comment]
yup

**Comment by jesstytam** [comment]
![h_tree](https://user-images.githubusercontent.com/51732676/108784219-03566c00-75c3-11eb-9503-cdd72749dbb3.png)
need to fix legend and figure out the species with the purple dot among the red area

**Comment by jesstytam** [comment]
![h_tree](https://user-images.githubusercontent.com/51732676/108802337-28aba000-75ec-11eb-900c-207c507a87ed.png)
clade fixed, but not the legend

**Comment by jesstytam** [comment]
![h_tree](https://user-images.githubusercontent.com/51732676/115351094-369b2d00-a1f9-11eb-9a18-46156ef76b52.png)
new font

**Comment by jesstytam** [comment]
![h_tree](https://user-images.githubusercontent.com/51732676/118085641-13cdf400-b406-11eb-9521-c288e65506b0.png)
will fix resolution and font size tmr

**Comment by jesstytam** [comment]
i made 2 tree plots but both of them are missing some important spp with very high h-index, i'm not sure which one i should use

this first one is the one i made with the list of mammal names parsed to rotl (n = 7148), but missing chimpanzee (rank 8), sheep, (rank 9), goat (rank 14) since OTL does not have tree information on them

![h_tree](https://user-images.githubusercontent.com/51732676/118598832-122f7200-b7f2-11eb-9831-10f726d5574a.png)

i've made this second one with one of the trees that we used in the model (n = 5518), but still missing chinese hamster (rank 10), goat (rank 14)

![h_tree2](https://user-images.githubusercontent.com/51732676/118598848-165b8f80-b7f2-11eb-969e-94933583942d.png)
