### ISSUE TITLE
body mass

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#34]
![logh_vs_logmass](https://user-images.githubusercontent.com/51732676/108014047-27fd9180-7061-11eb-9afe-aa75ecdccb6b.png)

**Comment by jesstytam** [comment]
![logh_vs_logmass](https://user-images.githubusercontent.com/51732676/108021697-33f24f00-7073-11eb-9e5f-4814970183e9.png)

**Comment by wcornwell** [comment]
maybe try quantile regression for this one? https://ggplot2.tidyverse.org/reference/geom_quantile.html

also try `scale_x_log10` so that the units on the x-axis are real.  (y-axis is harder problem...)

**Comment by jesstytam** [comment]
![logh_vs_logmass](https://user-images.githubusercontent.com/51732676/108138766-bf6eed00-7112-11eb-8415-423d30756332.png)
something like this?

**Comment by wcornwell** [comment]
nice one!  different slopes are very interesting!  I guess x-axis is kg?

**Comment by wcornwell** [comment]
For y-axis try this solution: https://github.com/tidyverse/ggplot2/issues/2980 ?

**Comment by jesstytam** [comment]
yes looks like marsupials and monotremes is slightly negative

**Comment by jesstytam** [comment]
![logh_vs_logmass](https://user-images.githubusercontent.com/51732676/108152392-11bd0780-712d-11eb-9080-883153f064e5.png)
is this better?

**Comment by jesstytam** [comment]
actually it looks exactly the same (except the lines are now curved), need to check why

**Comment by jesstytam** [comment]
![logh_vs_logmass](https://user-images.githubusercontent.com/51732676/114472446-92801780-9c35-11eb-971a-f09a36ec1f44.png)
fixed the scale and body mass values

**Comment by jesstytam** [comment]
![logh_vs_logmass](https://user-images.githubusercontent.com/51732676/115351025-25eab700-a1f9-11eb-8872-21d530dc7a12.png)
new font

**Comment by jesstytam** [comment]
![logh_vs_logmass](https://user-images.githubusercontent.com/51732676/116352556-b0a26600-a838-11eb-9a0e-0ca7f800d4ec.png)
new dataset, changed g to kg

**Comment by jesstytam** [comment]
![logh_vs_logmass](https://user-images.githubusercontent.com/51732676/116505324-e9f0d980-a8fd-11eb-8a8d-2c8d46682010.png)
added more ticks on the y-axis
