### ISSUE TITLE
domestication

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#35]
![logh_vs_domestication](https://user-images.githubusercontent.com/51732676/108014106-4794ba00-7061-11eb-8d2b-729a61e7e37d.png)

**Comment by wcornwell** [comment]
ggbeeswarm maybe

**Comment by jesstytam** [comment]
![logh_vs_domestication](https://user-images.githubusercontent.com/51732676/108133801-415a1880-7109-11eb-842a-33d4cc4a04f1.png)

**Comment by jesstytam** [comment]
![logh_vs_domestication](https://user-images.githubusercontent.com/51732676/108154071-6ada6a80-7130-11eb-9c68-2b6c690299af.png)

**Comment by jesstytam** [comment]
![logh_vs_domestication](https://user-images.githubusercontent.com/51732676/108300991-2c5ab380-71f5-11eb-98c0-e83a0255c435.png)
does this need a boxplot as well or clear enough?

**Comment by wcornwell** [comment]
i like the boxplot behind the beeswarm!

**Comment by jesstytam** [comment]
![logh_vs_domestication](https://user-images.githubusercontent.com/51732676/115500656-1761d580-a2b5-11eb-8e56-a466e0bd010f.png)
new font and new dataset, hence the slightly different spread

**Comment by jesstytam** [comment]
![logh_vs_domestication](https://user-images.githubusercontent.com/51732676/116505516-76030100-a8fe-11eb-9053-2109c7ba3116.png)
added more tick marks for h-index
