### ISSUE TITLE
h-index map

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#37]
![logh_map](https://user-images.githubusercontent.com/51732676/108014193-7743c200-7061-11eb-9521-aa694fa73476.png)

**Comment by wcornwell** [comment]
pretty good, except the scaling issue for the legend

**Comment by jesstytam** [comment]
![logh_map](https://user-images.githubusercontent.com/51732676/108159139-7d59a180-713a-11eb-9fe8-e59d87f50760.png)

**Comment by jesstytam** [comment]
![logh_map](https://user-images.githubusercontent.com/51732676/115350797-e3c17580-a1f8-11eb-9e98-43d2a8c1672f.png)
new font

**Comment by jesstytam** [comment]
![logh_map](https://user-images.githubusercontent.com/51732676/116505639-bbbfc980-a8fe-11eb-96d5-b492fc255f42.png)
fixed legend
