### ISSUE TITLE
human use

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#38]
![logh_vs_humanuse](https://user-images.githubusercontent.com/51732676/108014228-8f1b4600-7061-11eb-92a9-fcf15da72134.png)

**Comment by jesstytam** [comment]
merge y-axis

**Comment by jesstytam** [comment]
![logh_vs_humanuse](https://user-images.githubusercontent.com/51732676/108158437-053eac00-7139-11eb-82c5-9eaa064536b1.png)
should i use gghalves here as well?

**Comment by wcornwell** [comment]
> should i use gghalves here as well?

yeah i so, so it'll be easier for the reader to see the median of the more data-dense ones...

**Comment by jesstytam** [comment]
![logh_vs_humanuse](https://user-images.githubusercontent.com/51732676/108300374-565fa600-71f4-11eb-8211-1fd4ccb5d92d.png)
gghalves also not working here

**Comment by jesstytam** [comment]
![logh_vs_humanuse](https://user-images.githubusercontent.com/51732676/115350752-d4dac300-a1f8-11eb-94b3-95de11d3156e.png)
new font

**Comment by jesstytam** [comment]
![logh_vs_humanuse](https://user-images.githubusercontent.com/51732676/116505706-f590d000-a8fe-11eb-8fb2-d629008f61f7.png)
added more tick marks for h-index
