### ISSUE TITLE
latitude

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#39]
![logh_vs_lat](https://user-images.githubusercontent.com/51732676/108014370-cee22d80-7061-11eb-879b-f94c55d61965.png)

**Comment by jesstytam** [comment]
add gam

**Comment by jesstytam** [comment]
![logh_vs_lat](https://user-images.githubusercontent.com/51732676/108021318-6b143080-7072-11eb-816f-f7b2da0241fd.png)

**Comment by wcornwell** [comment]
gam looks good!

**Comment by wcornwell** [comment]
so at the equator, the average mammal has an h-index of 2 and at 40 degrees it's about 7?

**Comment by jesstytam** [comment]
yup, looks like it

**Comment by jesstytam** [comment]
![logh_vs_lat](https://user-images.githubusercontent.com/51732676/108152924-382f7280-712e-11eb-9a07-c536092a5831.png)
should i keep the histogram? it only shows species diversity

**Comment by jesstytam** [comment]
![logh_vs_lat](https://user-images.githubusercontent.com/51732676/115350627-b1177d00-a1f8-11eb-80db-87c1c2370737.png)
new font

**Comment by jesstytam** [comment]
![logh_vs_lat](https://user-images.githubusercontent.com/51732676/116505758-122d0800-a8ff-11eb-824e-32d60e9d9aa4.png)
added more tick marks for h-index and added degree symbol
