### ISSUE TITLE
correlation matrix

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#43]
![correlation_matrix](https://user-images.githubusercontent.com/51732676/109735954-b94f3500-7c17-11eb-916a-03564352011f.png)

**Comment by itchyshin** [comment]
@jessicatytam - nice!!

**Comment by jesstytam** [comment]
![correlation_matrix](https://user-images.githubusercontent.com/51732676/109752963-73a16500-7c35-11eb-81b9-55c27a1f5fc1.png)
updated version because i had forgotten to change some variables to discrete from continous

**Comment by jesstytam** [comment]
and i've also switch from log10(h+1) to real h

**Comment by itchyshin** [comment]
@jessicatytam - an excellent job!!
