### ISSUE TITLE
phylogenetic signal

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#45]
get branch lengths from nature paper

**Comment by jesstytam** [comment]
@itchyshin run mcmcglmm + estimate hours
@wcornwell help @jessicatytam calculate phylo signal

**Comment by mlagisz** [comment]
Plos Biol 2019 paper - mammalian tree with branch lengths: https://pubmed.ncbi.nlm.nih.gov/31800571/

**Comment by jesstytam** [comment]
try this http://www.phytools.org/static.help/phylosig.html

**Comment by jesstytam** [comment]
there are only 4881 overlapping mammals
using phylosig() right now but it seems to crach everytime i try to run it

**Comment by itchyshin** [comment]
@jessicatytam - could you come to see me tomorrow - how about 12? - midday

**Comment by itchyshin** [comment]
I mean Friday 19th (before you disappear into the middle of nowhere!)

**Comment by jesstytam** [comment]
Yup sure 👍🏼

**Comment by jesstytam** [comment]
![image](https://user-images.githubusercontent.com/51732676/111719009-1a7d3680-88af-11eb-99e7-7fe81e304f07.png)

**Comment by itchyshin** [comment]
So as I expected - body mass has the highest signal @jessicatytam - thanks

**Comment by jesstytam** [comment]
oh cool, i thought lower k means that the signal is lower 👍🏽

**Comment by itchyshin** [comment]
@jessicatytam you are correct but log(mass) has the highest k - others are much lower
