### ISSUE TITLE
check for missing data

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#46]
check if mammals with higher h-index have less missing data
convert data to binary (1 for data present, 0 for data missing)

**Comment by jesstytam** [comment]
Welch Two Sample t-test

data:  includeh$complete and includeh$h
t = -30.008, df = 6805.1, p-value < 2.2e-16
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -5.313135 -4.661527
sample estimates:
mean of x mean of y 
0.4998527 5.4871833

**Comment by itchyshin** [comment]
@jessicatytam - excellent - so we need to impute - once you had a look at my analysis, set up a meeting.

Note I am away between 14-19th
