### ISSUE TITLE
ultrametric trees

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#48]
@wcornwell  how do we make a non-ultrametric tree ultrametric?

**Comment by jesstytam** [comment]
should we use phytools::force.ultrametric?

**Comment by wcornwell** [comment]
which tree is it?

**Comment by wcornwell** [comment]
depends why it's non-ultrametric...

**Comment by jesstytam** [comment]
the new trees from http://vertlife.org/data/mammals/

**Comment by wcornwell** [comment]
hmmm they say the trees are ultrametric.  I've come across this before--i think it's a bug, possibly in ape's read in function.  Maybe try `phytools::read.newick` or `phytools::force.ultrametric`?

**Comment by jesstytam** [comment]
ok i'll try and see if it works

**Comment by jesstytam** [comment]
`phytools::force.ultrametric` is working

**Comment by itchyshin** [comment]
@jessicatytam - but this is not a good solution? @wcornwell - this is what I first suggested - is it the best option?

I guess it was nearly an ultrametric tree so it does not really matter if you use any methods - even in `forec.ultrametric()` we can use 2 different methods

**Comment by wcornwell** [comment]
yeah should be fine.  

They've already done the dating and smoothing thing on those trees, so they *should* be ultrametric to start with.  

Why `ape` isn't reading them as ultrametric is an interesting question.  It could be 1) a rounding issue on the branch lengths or 2) a weird bug in `ape::read.tree`, and for either issue `phytools::force.ultrametric` should be fine.

**Comment by jesstytam** [comment]
solved by `phytools::force.ultrametric`
