### ISSUE TITLE
plots for main text

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#51]
![pub_ridge](https://user-images.githubusercontent.com/51732676/119495104-5f3cb680-bda5-11eb-9a9d-e31c6a1c9efb.png)
number of publications, need clearer order labels

![pub_proportion](https://user-images.githubusercontent.com/51732676/119494991-4207e800-bda5-11eb-8527-72e582204a72.png)
proportion of publications, need to find out what happened in the 50s

![grid_plot](https://user-images.githubusercontent.com/51732676/119494836-1684fd80-bda5-11eb-9c7f-5867f6b203d4.png)
summary of findings, label the subplots with a/b/c/d/e/f/g

maybe make another one showing the top 20 mammals?

**Comment by itchyshin** [comment]
@jessicatytam - looking fab!

**Comment by jesstytam** [comment]
![grid_plot](https://user-images.githubusercontent.com/51732676/119754295-9e712180-bee3-11eb-9437-552585018295.png)
added labels, and increased transparency

![h100](https://user-images.githubusercontent.com/51732676/119753834-c7dd7d80-bee2-11eb-8536-1dfaad7f10c1.png)
species with h-index > 100, will add animals photos / silhouette

**Comment by jesstytam** [comment]
![pub_plot_combine](https://user-images.githubusercontent.com/51732676/119762426-0aa65200-bef1-11eb-8940-57cd409b17ca.png)
combined ggstream plots

![grid_plot](https://user-images.githubusercontent.com/51732676/119763372-be5c1180-bef2-11eb-9d7f-47366bdedf9b.png)
fixed scale and panel grid

**Comment by jesstytam** [comment]
![h100](https://user-images.githubusercontent.com/51732676/119767349-003c8600-befa-11eb-9799-8b391194212e.png)
colour by order

**Comment by jesstytam** [comment]
![h100_text](https://user-images.githubusercontent.com/51732676/120058574-38c19880-c08f-11eb-9fd1-f7a4ed4e881f.jpg)

**Comment by itchyshin** [comment]
Wow, beautiful! @jessicatytam

**Comment by jesstytam** [comment]
![grid_plot](https://user-images.githubusercontent.com/51732676/121990145-a59f9700-cde0-11eb-9e61-f09d9b763bab.png)
added boxplot

**Comment by jesstytam** [comment]
![grid_plot](https://user-images.githubusercontent.com/51732676/122005674-4601b580-cdf9-11eb-860e-19eb2f420865.png)
added geom_rug to (b) to show species distribution

**Comment by jesstytam** [comment]
![maps_plot](https://user-images.githubusercontent.com/51732676/122321944-03aab680-cf68-11eb-82cb-d7f941ffb135.png)
new map plot showing location bias

![pub_plot_combine](https://user-images.githubusercontent.com/51732676/122322012-1b823a80-cf68-11eb-93d2-fc2dfe2637ce.png)
previous ggstream plot was missing 2 orders, this is fixed now

**Comment by wcornwell** [comment]
maybe try this: https://rud.is/b/2018/09/28/quick-hit-using-the-new-equal-earth-projection-in-r/ for maps

**Comment by jesstytam** [comment]
![grid_plot](https://user-images.githubusercontent.com/51732676/171070872-41f213e1-44eb-4f7a-825b-848b708322d5.png)
updated iucn categories for panel

**Comment by mlagisz** [comment]
Thank you! Looks good! How about moving panel titles to the top of each panel (and move the legend to the bottom)?
