### ISSUE TITLE
iucn vs gbif latitude

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#52]
I did a correlation test and here's the result

	Pearson's product-moment correlation

data:  y$mean and y$y
t = 205.47, df = 3932, p-value < 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.9537053 0.9590353
sample estimates:
    cor 
0.95645 

and a plot 
![image](https://user-images.githubusercontent.com/51732676/154386924-e7518a53-5c8a-49ed-a825-92a572277b36.png)

pretty close?

**Comment by itchyshin** [comment]
@jessicatytam - it is very very close - we can mention the correlation.

Some look quite different tho. @wcornwell should we use the original one or this one? - but if we use this one, we need to rerun the original models too - so we want to stick with the original one.

Jess once you check with Will - you can start running these new models without domesticated species as discussed

**Comment by itchyshin** [comment]
@jessicatytam - Before you run models - you may want to double-check with me - I can make sure things all well. 

BTW - please send @wcornwell + @mlagisz (us) a to-do list for the JOSS paper too (so we can sort it out on Tuesday - please do this by Monday if possible)
