### ISSUE TITLE
Turning into a package

### ISSUE THREAD

**Issue by wcornwell** [jessicatytam/Honours#6]
see http://r-pkgs.had.co.nz/

**Comment by wcornwell** [comment]
@jessicatytam better explanation of what I was trying to say is here: http://r-pkgs.had.co.nz/man.html#man-functions

**Comment by jessicatytam** [comment]
ok thanks, just to confirm I'm doing the documentation in the .r file?

**Comment by itchyshin** [comment]
Yes @jessicatytam

**Comment by wcornwell** [comment]
here is the workflow overview: http://r-pkgs.had.co.nz/man.html#man-workflow

**Comment by wcornwell** [comment]
@jessicatytam do you want me to copy some of the generic package files into the directory so `devtools::document()` will work?

**Comment by jessicatytam** [comment]
ok sure that would be nice thanks!

**Comment by wcornwell** [comment]
hmmm it wants the name of the repository to be the same as the name of the package.  So many we can change it from "Honours" to "specieshindex" ???

**Comment by jessicatytam** [comment]
that should be fine? hopefully
we should be able to rename it in the future?

**Comment by wcornwell** [comment]
yeah i think so

**Comment by wcornwell** [comment]
ok try pulling and then try `devtools::document()` and see if it works for you

**Comment by wcornwell** [comment]
seems like this is done
